import datetime as dt
import json
import os
import subprocess
import urllib.parse
from pathlib import Path

import pytest

import github_code_harvester.harvester as harvester
from github_code_harvester.harvester import (
    CODE_EXTENSIONS,
    CommitInfo,
    RepoInfo,
    build_record,
    checkout_commit,
    clone_or_update_repo,
    cleanup_project_workspace,
    failed_log_main,
    fetch_high_star_repos,
    fetch_gitlab_project,
    fetch_high_star_gitlab_projects,
    gitlab_project_to_repo,
    ensure_repo_csv_finished_field,
    is_code_commit,
    is_eligible_repo,
    infer_project_type,
    load_failed_repos_from_csv,
    read_failed_repo_names,
    merge_commit_jsons_to_jsonl,
    mark_repo_finished,
    process_repo,
    process_repo_to_commit_jsons,
    read_repo_csv,
    resolve_token,
    remove_repos_from_failure_log,
    repo_to_csv_row,
    run_pipeline,
    select_eligible_repos,
    append_repo_csv,
    filter_unfinished_repos,
    write_repo_csv,
    write_jsonl_for_commit,
    parse_stackoverflow_args,
    repo_has_commit_since_via_api,
    stackoverflow_question_to_record,
    write_stackoverflow_records,
)


def test_rejects_tutorial_examples_and_generated_datasets():
    repo = RepoInfo(
        full_name="owner/python-tutorial",
        clone_url="https://github.com/owner/python-tutorial.git",
        html_url="https://github.com/owner/python-tutorial",
        language="Python",
        stargazers_count=50_000,
        description="Synthetic examples generated by an LLM for teaching.",
        topics=["tutorial", "synthetic-data"],
        pushed_at="2026-01-02T03:04:05Z",
    )

    assert is_eligible_repo(repo) is False


def test_accepts_real_high_star_application_repo():
    repo = RepoInfo(
        full_name="owner/production-api",
        clone_url="https://github.com/owner/production-api.git",
        html_url="https://github.com/owner/production-api",
        language="Go",
        stargazers_count=20_000,
        description="A scalable production API server and service framework.",
        topics=["api", "server", "database"],
        pushed_at="2026-01-02T03:04:05Z",
    )

    assert is_eligible_repo(repo) is True


def test_repo_to_csv_row_and_write_repo_csv(tmp_path: Path):
    repo = RepoInfo(
        full_name="owner/production-api",
        clone_url="https://github.com/owner/production-api.git",
        html_url="https://github.com/owner/production-api",
        language="Go",
        stargazers_count=20_000,
        description="A scalable production API server and service framework.",
        topics=["api", "server", "database"],
        pushed_at="2026-01-02T03:04:05Z",
    )
    csv_path = tmp_path / "group_repo.csv"

    write_repo_csv([repo], csv_path)

    assert repo_to_csv_row(repo) == {
        "group_repo": "owner/production-api",
        "url": "https://github.com/owner/production-api",
        "language": "Go",
        "star": "20000",
        "author": "owner",
        "project_type": "网站后端",
        "finished": "false",
    }
    assert csv_path.read_text(encoding="utf-8").splitlines() == [
        "group_repo,url,language,star,author,project_type,finished",
        "owner/production-api,https://github.com/owner/production-api,Go,20000,owner,网站后端,false",
    ]


def test_read_repo_csv_reconstructs_repo_info(tmp_path: Path):
    csv_path = tmp_path / "group_repo.csv"
    csv_path.write_text(
        "group_repo,url,language,star,author,project_type\n"
        "owner/production-api,https://github.com/owner/production-api,Go,20000,owner,网站后端\n",
        encoding="utf-8",
    )

    repos = read_repo_csv(csv_path)

    assert repos == [
        RepoInfo(
            full_name="owner/production-api",
            clone_url="https://github.com/owner/production-api.git",
            html_url="https://github.com/owner/production-api",
            language="Go",
            stargazers_count=20_000,
            description="",
            topics=[],
            pushed_at="",
            finished=False,
        )
    ]


def test_append_repo_csv_preserves_existing_and_appends_new_unique(tmp_path: Path):
    csv_path = tmp_path / "group_repo.csv"
    existing = RepoInfo(
        full_name="owner/existing",
        clone_url="https://github.com/owner/existing.git",
        html_url="https://github.com/owner/existing",
        language="Python",
        stargazers_count=9_000,
        description="Existing repo.",
        topics=[],
        pushed_at="",
    )
    duplicate = RepoInfo(
        full_name="owner/existing",
        clone_url="https://github.com/owner/existing.git",
        html_url="https://github.com/owner/existing",
        language="Python",
        stargazers_count=9_000,
        description="Duplicate repo.",
        topics=[],
        pushed_at="",
    )
    new_repo = RepoInfo(
        full_name="owner/new",
        clone_url="https://github.com/owner/new.git",
        html_url="https://github.com/owner/new",
        language="Go",
        stargazers_count=12_000,
        description="Production API server.",
        topics=["api"],
        pushed_at="",
    )
    write_repo_csv([existing], csv_path)

    appended = append_repo_csv([duplicate, new_repo], csv_path)

    all_repos = read_repo_csv(csv_path)
    assert appended == [new_repo]
    assert [repo.full_name for repo in all_repos] == ["owner/existing", "owner/new"]
    assert [repo.finished for repo in all_repos] == [False, False]


def test_fetch_high_star_repos_skips_existing_and_continues_pages(monkeypatch):
    calls: list[str] = []

    def fake_github_get_json(url: str, github_token: str | None) -> dict:
        calls.append(url)
        query = urllib.parse.parse_qs(urllib.parse.urlparse(url).query)
        if query.get("page") == ["1"]:
            return {
                "items": [
                    {
                        "full_name": "owner/existing",
                        "clone_url": "https://github.com/owner/existing.git",
                        "html_url": "https://github.com/owner/existing",
                        "language": "Go",
                        "stargazers_count": 20_000,
                        "description": "Existing production server.",
                        "topics": ["server"],
                        "pushed_at": "",
                    }
                ]
            }
        return {
            "items": [
                {
                    "full_name": "owner/new",
                    "clone_url": "https://github.com/owner/new.git",
                    "html_url": "https://github.com/owner/new",
                    "language": "Go",
                    "stargazers_count": 15_000,
                    "description": "New production server.",
                    "topics": ["server"],
                    "pushed_at": "",
                }
            ]
        }

    monkeypatch.setattr(harvester, "github_get_json", fake_github_get_json)

    repos = fetch_high_star_repos(
        languages=["Go"],
        min_stars=5_000,
        repos_per_language=1,
        max_repos=1,
        existing_repo_names={"owner/existing"},
        search_max_pages=2,
    )

    assert [repo.full_name for repo in repos] == ["owner/new"]
    assert len(calls) == 2


def test_fetch_high_star_repos_caps_github_search_pages(monkeypatch):
    calls: list[int] = []

    def fake_github_get_json(url: str, github_token: str | None) -> dict:
        query = urllib.parse.parse_qs(urllib.parse.urlparse(url).query)
        calls.append(int(query["page"][0]))
        return {
            "items": [
                {
                    "full_name": "owner/existing",
                    "clone_url": "https://github.com/owner/existing.git",
                    "html_url": "https://github.com/owner/existing",
                    "language": "Go",
                    "stargazers_count": 20_000,
                    "description": "Existing production server.",
                    "topics": ["server"],
                    "pushed_at": "",
                }
            ]
        }

    monkeypatch.setattr(harvester, "github_get_json", fake_github_get_json)

    repos = fetch_high_star_repos(
        languages=["Go"],
        min_stars=5_000,
        repos_per_language=1,
        max_repos=1,
        existing_repo_names={"owner/existing"},
        search_max_pages=100,
    )

    assert repos == []
    assert calls == list(range(1, 11))


def test_filter_unfinished_repos_skips_finished_csv_records():
    done_repo = RepoInfo(
        full_name="owner/done",
        clone_url="https://github.com/owner/done.git",
        html_url="https://github.com/owner/done",
        language="Python",
        stargazers_count=10_000,
        description="Done repo.",
        topics=[],
        pushed_at="",
        finished=True,
    )
    pending_repo = RepoInfo(
        full_name="owner/pending",
        clone_url="https://github.com/owner/pending.git",
        html_url="https://github.com/owner/pending",
        language="Go",
        stargazers_count=11_000,
        description="Pending repo.",
        topics=[],
        pushed_at="",
    )

    assert filter_unfinished_repos([done_repo, pending_repo]) == [pending_repo]


def test_mark_repo_finished_updates_csv_without_touching_other_rows(tmp_path: Path):
    csv_path = tmp_path / "group_repo.csv"
    csv_path.write_text(
        "group_repo,url,language,star,author,project_type,finished\n"
        "owner/done,https://github.com/owner/done,Go,20000,owner,网站后端,false\n"
        "owner/pending,https://github.com/owner/pending,Python,12000,owner,命令行工具,false\n",
        encoding="utf-8",
    )

    mark_repo_finished(csv_path, "owner/done")

    rows = csv_path.read_text(encoding="utf-8").splitlines()
    assert rows == [
        "group_repo,url,language,star,author,project_type,finished",
        "owner/done,https://github.com/owner/done,Go,20000,owner,网站后端,true",
        "owner/pending,https://github.com/owner/pending,Python,12000,owner,命令行工具,false",
    ]


def test_ensure_repo_csv_finished_field_adds_default_false_to_existing_csv(tmp_path: Path):
    csv_path = tmp_path / "group_repo.csv"
    csv_path.write_text(
        "group_repo,url,language,star,author,project_type\n"
        "owner/pending,https://github.com/owner/pending,Python,12000,owner,命令行工具\n",
        encoding="utf-8",
    )

    ensure_repo_csv_finished_field(csv_path)

    assert csv_path.read_text(encoding="utf-8").splitlines() == [
        "group_repo,url,language,star,author,project_type,finished",
        "owner/pending,https://github.com/owner/pending,Python,12000,owner,命令行工具,false",
    ]


def test_read_failed_repo_names_parses_unique_repo_names(tmp_path: Path):
    failure_log = tmp_path / "failed_repos.log"
    failure_log.write_text(
        "2026-06-14T00:00:00+00:00\towner/one\tclone\tnetwork failed\n"
        "2026-06-14T00:01:00+00:00\towner/two\tprocess\tbad commit\n"
        "2026-06-14T00:02:00+00:00\towner/one\tclone\tretry failed\n",
        encoding="utf-8",
    )

    assert read_failed_repo_names(failure_log) == {"owner/one", "owner/two"}


def test_load_failed_repos_from_csv_selects_only_unfinished_failed_names_without_rewriting_csv(tmp_path: Path):
    csv_path = tmp_path / "group_repo.csv"
    csv_path.write_text(
        "group_repo,url,language,star,author,project_type,finished\n"
        "owner/failed,https://github.com/owner/failed,Go,20000,owner,网站后端,false\n"
        "owner/already-done,https://github.com/owner/already-done,Go,20000,owner,网站后端,true\n"
        "owner/done,https://github.com/owner/done,Python,12000,owner,命令行工具,true\n",
        encoding="utf-8",
    )
    failure_log = tmp_path / "failed_repos.log"
    failure_log.write_text(
        "2026-06-14T00:00:00+00:00\towner/failed\tclone\tnetwork failed\n"
        "2026-06-14T00:00:00+00:00\towner/already-done\tprocess\tno qualifying commits\n",
        encoding="utf-8",
    )

    repos = load_failed_repos_from_csv(csv_path, failure_log)

    assert [repo.full_name for repo in repos] == ["owner/failed"]
    assert repos[0].finished is False
    assert "owner/already-done,https://github.com/owner/already-done,Go,20000,owner,网站后端,true" in csv_path.read_text(encoding="utf-8")


def test_failed_log_main_processes_only_failed_repos_without_resetting_csv(tmp_path: Path, monkeypatch):
    csv_path = tmp_path / "group_repo.csv"
    csv_path.write_text(
        "group_repo,url,language,star,author,project_type,finished\n"
        "owner/failed,https://github.com/owner/failed,Go,20000,owner,网站后端,false\n"
        "owner/done,https://github.com/owner/done,Python,12000,owner,命令行工具,true\n",
        encoding="utf-8",
    )
    output_dir = tmp_path / "final_data"
    output_dir.mkdir()
    failure_log = output_dir / "failed_repos.log"
    failure_log.write_text(
        "2026-06-14T00:00:00+00:00\towner/failed\tclone\tnetwork failed\n",
        encoding="utf-8",
    )
    seen: dict[str, object] = {}

    def fake_run_pipeline(**kwargs):
        seen["repos"] = kwargs["repos"]
        seen["repo_csv_path"] = kwargs["repo_csv_path"]

    monkeypatch.setattr(harvester, "run_pipeline", fake_run_pipeline)

    assert failed_log_main(
        [
            "--repo-csv",
            str(csv_path),
            "--output-dir",
            str(output_dir),
            "--work-dir",
            str(tmp_path / "repos"),
            "--commit-work-dir",
            str(tmp_path / "commit_json"),
        ]
    ) == 0

    repos = seen["repos"]
    assert [repo.full_name for repo in repos] == ["owner/failed"]
    assert repos[0].finished is False
    assert seen["repo_csv_path"] == csv_path
    assert read_repo_csv(csv_path)[0].finished is False


def test_failed_log_main_skips_failed_repos_already_marked_finished(tmp_path: Path, monkeypatch, capsys):
    csv_path = tmp_path / "group_repo.csv"
    csv_path.write_text(
        "group_repo,url,language,star,author,project_type,finished\n"
        "owner/no-commits,https://github.com/owner/no-commits,Go,20000,owner,网站后端,true\n",
        encoding="utf-8",
    )
    output_dir = tmp_path / "final_data"
    output_dir.mkdir()
    failure_log = output_dir / "failed_repos.log"
    failure_log.write_text(
        "2026-06-14T00:00:00+00:00\towner/no-commits\tprocess\tno qualifying commits\n",
        encoding="utf-8",
    )
    monkeypatch.setattr(harvester, "run_pipeline", lambda **kwargs: pytest.fail("should not run pipeline"))

    assert failed_log_main(
        [
            "--repo-csv",
            str(csv_path),
            "--output-dir",
            str(output_dir),
        ]
    ) == 0

    output = capsys.readouterr().out
    assert "Loaded 0 failed repositories" in output
    assert "No failed repositories to process" in output


def test_remove_repos_from_failure_log_deletes_successful_entries(tmp_path: Path):
    failure_log = tmp_path / "failed_repos.log"
    failure_log.write_text(
        "2026-06-14T00:00:00+00:00\towner/recovered\tclone\tnetwork failed\n"
        "2026-06-14T00:01:00+00:00\towner/still-broken\tprocess\tbad commit\n",
        encoding="utf-8",
    )

    remove_repos_from_failure_log(failure_log, {"owner/recovered"})

    assert failure_log.read_text(encoding="utf-8").splitlines() == [
        "2026-06-14T00:01:00+00:00\towner/still-broken\tprocess\tbad commit",
    ]


def test_run_pipeline_records_failed_repo_without_raising(tmp_path: Path, monkeypatch):
    repo = RepoInfo(
        full_name="owner/broken",
        clone_url="https://github.com/owner/broken.git",
        html_url="https://github.com/owner/broken",
        language="Python",
        stargazers_count=10_000,
        description="Broken repo.",
        topics=[],
        pushed_at="",
    )

    def fail_clone(repo: RepoInfo, work_dir: Path, since: str | None = None) -> Path:
        raise RuntimeError("network failed")

    monkeypatch.setattr(harvester, "clone_or_update_repo", fail_clone)

    run_pipeline(
        repos=[repo],
        work_dir=tmp_path / "repos",
        output_dir=tmp_path / "final_data",
        commit_work_dir=tmp_path / "commit_json",
        since="2025-10-01",
        jsonl_workers=1,
        clone_workers=1,
    )

    failure_log = tmp_path / "final_data" / "failed_repos.log"
    assert failure_log.exists()
    assert "owner/broken" in failure_log.read_text(encoding="utf-8")
    assert "network failed" in failure_log.read_text(encoding="utf-8")


def test_run_pipeline_logs_commit_scan_summary_when_no_jsonl(tmp_path: Path, monkeypatch, capsys):
    repo = RepoInfo(
        full_name="owner/no-code",
        clone_url="https://github.com/owner/no-code.git",
        html_url="https://github.com/owner/no-code",
        language="Python",
        stargazers_count=10_000,
        description="Docs only.",
        topics=[],
        pushed_at="",
    )
    repo_dir = tmp_path / "repo"
    repo_dir.mkdir()

    monkeypatch.setattr(harvester, "clone_or_update_repo", lambda repo, work_dir, since=None: repo_dir)
    monkeypatch.setattr(harvester, "list_commits_since", lambda repo_dir, since: ["abc123"])
    monkeypatch.setattr(
        harvester,
        "get_commit_info",
        lambda repo_dir, sha: CommitInfo(
            sha=sha,
            author="Docs Author",
            author_date=dt.datetime(2026, 1, 1, tzinfo=dt.UTC),
            changed_files=["README.md"],
        ),
    )

    run_pipeline(
        repos=[repo],
        work_dir=tmp_path / "repos",
        output_dir=tmp_path / "final_data",
        commit_work_dir=tmp_path / "commit_json",
        since="2025-10-01",
        jsonl_workers=1,
        clone_workers=1,
    )

    output = capsys.readouterr().out
    assert "Processing 1 repositories with clone_workers=1, workers=1, since=2025-10-01" in output
    assert "owner/no-code: clone start" in output
    assert "owner/no-code: clone done" in output
    assert "owner/no-code: found 1 commits since 2025-10-01" in output
    assert "owner/no-code: commit scan summary scanned=1 metadata_missing=0 non_code=1 eligible=0 written=0 empty_records=0" in output
    assert "owner/no-code: wrote 0 records; no final jsonl created" in output


def test_run_pipeline_marks_repo_finished_when_no_qualifying_commits(tmp_path: Path, monkeypatch):
    repo = RepoInfo(
        full_name="owner/no-commits",
        clone_url="https://github.com/owner/no-commits.git",
        html_url="https://github.com/owner/no-commits",
        language="Go",
        stargazers_count=10_000,
        description="No recent commits.",
        topics=[],
        pushed_at="",
    )
    csv_path = tmp_path / "group_repo.csv"
    write_repo_csv([repo], csv_path)
    repo_dir = tmp_path / "repo"
    repo_dir.mkdir()

    monkeypatch.setattr(harvester, "clone_or_update_repo", lambda repo, work_dir, since=None: repo_dir)
    monkeypatch.setattr(harvester, "list_commits_since", lambda repo_dir, since: [])

    run_pipeline(
        repos=[repo],
        work_dir=tmp_path / "repos",
        output_dir=tmp_path / "final_data",
        commit_work_dir=tmp_path / "commit_json",
        since="2025-10-01",
        jsonl_workers=1,
        clone_workers=1,
        repo_csv_path=csv_path,
    )

    assert read_repo_csv(csv_path)[0].finished is True


def test_run_pipeline_skips_clone_when_api_latest_commit_is_before_since(tmp_path: Path, monkeypatch, capsys):
    repo = RepoInfo(
        full_name="owner/stale",
        clone_url="https://github.com/owner/stale.git",
        html_url="https://github.com/owner/stale",
        language="Go",
        stargazers_count=10_000,
        description="Stale repo.",
        topics=[],
        pushed_at="",
    )
    csv_path = tmp_path / "group_repo.csv"
    write_repo_csv([repo], csv_path)

    monkeypatch.setattr(harvester, "repo_has_commit_since_via_api", lambda repo, since: False)
    monkeypatch.setattr(harvester, "clone_or_update_repo", lambda repo, work_dir, since=None: pytest.fail("should not clone stale repo"))

    run_pipeline(
        repos=[repo],
        work_dir=tmp_path / "repos",
        output_dir=tmp_path / "final_data",
        commit_work_dir=tmp_path / "commit_json",
        since="2025-10-01",
        jsonl_workers=1,
        clone_workers=1,
        repo_csv_path=csv_path,
    )

    output = capsys.readouterr().out
    assert "owner/stale: API precheck found no commits since 2025-10-01; skipping clone" in output
    assert read_repo_csv(csv_path)[0].finished is True


def test_run_pipeline_continues_clone_when_api_precheck_is_unknown(tmp_path: Path, monkeypatch):
    repo = RepoInfo(
        full_name="owner/unknown",
        clone_url="https://github.com/owner/unknown.git",
        html_url="https://github.com/owner/unknown",
        language="Go",
        stargazers_count=10_000,
        description="Repo with API failure.",
        topics=[],
        pushed_at="",
    )
    repo_dir = tmp_path / "repo"
    repo_dir.mkdir()
    seen = {"cloned": False}

    monkeypatch.setattr(harvester, "repo_has_commit_since_via_api", lambda repo, since: None)

    def fake_clone(repo: RepoInfo, work_dir: Path, since: str | None = None) -> Path:
        seen["cloned"] = True
        return repo_dir

    monkeypatch.setattr(harvester, "clone_or_update_repo", fake_clone)
    monkeypatch.setattr(harvester, "list_commits_since", lambda repo_dir, since: [])

    run_pipeline(
        repos=[repo],
        work_dir=tmp_path / "repos",
        output_dir=tmp_path / "final_data",
        commit_work_dir=tmp_path / "commit_json",
        since="2025-10-01",
        jsonl_workers=1,
        clone_workers=1,
    )

    assert seen["cloned"] is True


def test_run_pipeline_logs_api_precheck_error_and_continues_clone(tmp_path: Path, monkeypatch, capsys):
    repo = RepoInfo(
        full_name="owner/rate-limited",
        clone_url="https://github.com/owner/rate-limited.git",
        html_url="https://github.com/owner/rate-limited",
        language="Go",
        stargazers_count=10_000,
        description="Repo with API rate limit.",
        topics=[],
        pushed_at="",
    )
    repo_dir = tmp_path / "repo"
    repo_dir.mkdir()
    seen = {"cloned": False}

    def fail_precheck(repo: RepoInfo, since: str) -> bool | None:
        raise RuntimeError("HTTP Error 429: Too Many Requests")

    def fake_clone(repo: RepoInfo, work_dir: Path, since: str | None = None) -> Path:
        seen["cloned"] = True
        return repo_dir

    monkeypatch.setattr(harvester, "repo_has_commit_since_via_api", fail_precheck)
    monkeypatch.setattr(harvester, "clone_or_update_repo", fake_clone)
    monkeypatch.setattr(harvester, "list_commits_since", lambda repo_dir, since: [])

    run_pipeline(
        repos=[repo],
        work_dir=tmp_path / "repos",
        output_dir=tmp_path / "final_data",
        commit_work_dir=tmp_path / "commit_json",
        since="2025-10-01",
        jsonl_workers=1,
        clone_workers=1,
    )

    output = capsys.readouterr().out
    assert seen["cloned"] is True
    assert "owner/rate-limited: API precheck failed (HTTP Error 429: Too Many Requests); continuing with clone" in output
    assert not (tmp_path / "final_data" / "failed_repos.log").exists()


def test_repo_has_commit_since_via_api_uses_latest_github_commit_date(monkeypatch):
    repo = RepoInfo(
        full_name="owner/recent",
        clone_url="https://github.com/owner/recent.git",
        html_url="https://github.com/owner/recent",
        language="Go",
        stargazers_count=10_000,
        description="Recent repo.",
        topics=[],
        pushed_at="",
    )
    seen: dict[str, object] = {}

    def fake_github_get_json(url: str, github_token: str | None) -> list[dict]:
        seen["url"] = url
        seen["token"] = github_token
        return [{"commit": {"author": {"date": "2025-11-02T03:04:05Z"}}}]

    monkeypatch.setattr(harvester, "github_get_json", fake_github_get_json)
    monkeypatch.setattr(harvester, "resolve_token", lambda explicit, provider, env_name: "github-token")

    assert repo_has_commit_since_via_api(repo, "2025-10-01") is True
    assert seen == {
        "url": "https://api.github.com/repos/owner/recent/commits?per_page=1",
        "token": "github-token",
    }


def test_repo_has_commit_since_via_api_returns_false_for_stale_github_commit(monkeypatch):
    repo = RepoInfo(
        full_name="owner/stale",
        clone_url="https://github.com/owner/stale.git",
        html_url="https://github.com/owner/stale",
        language="Go",
        stargazers_count=10_000,
        description="Stale repo.",
        topics=[],
        pushed_at="",
    )

    monkeypatch.setattr(
        harvester,
        "github_get_json",
        lambda url, github_token: [{"commit": {"author": {"date": "2025-07-16T19:42:23Z"}}}],
    )

    assert repo_has_commit_since_via_api(repo, "2025-10-01") is False


def test_run_pipeline_marks_repo_finished_after_success(tmp_path: Path, monkeypatch):
    repo = RepoInfo(
        full_name="owner/done",
        clone_url="https://github.com/owner/done.git",
        html_url="https://github.com/owner/done",
        language="Go",
        stargazers_count=10_000,
        description="Done repo.",
        topics=[],
        pushed_at="",
    )
    csv_path = tmp_path / "group_repo.csv"
    write_repo_csv([repo], csv_path)
    repo_dir = tmp_path / "repo"
    repo_dir.mkdir()

    monkeypatch.setattr(harvester, "clone_or_update_repo", lambda repo, work_dir, since=None: repo_dir)
    monkeypatch.setattr(harvester, "process_repo_to_commit_jsons", lambda **kwargs: 1)
    monkeypatch.setattr(
        harvester,
        "merge_commit_jsons_to_jsonl",
        lambda commit_dir, final_dir, repo: final_dir / "owner__done.jsonl",
    )

    run_pipeline(
        repos=[repo],
        work_dir=tmp_path / "repos",
        output_dir=tmp_path / "final_data_github",
        commit_work_dir=tmp_path / "commit_json",
        since="2025-10-01",
        jsonl_workers=1,
        clone_workers=1,
        repo_csv_path=csv_path,
    )

    assert read_repo_csv(csv_path)[0].finished is True


def test_run_pipeline_removes_recovered_repo_from_failure_log(tmp_path: Path, monkeypatch):
    recovered = RepoInfo(
        full_name="owner/recovered",
        clone_url="https://github.com/owner/recovered.git",
        html_url="https://github.com/owner/recovered",
        language="Go",
        stargazers_count=10_000,
        description="Recovered repo.",
        topics=[],
        pushed_at="",
    )
    still_broken = RepoInfo(
        full_name="owner/still-broken",
        clone_url="https://github.com/owner/still-broken.git",
        html_url="https://github.com/owner/still-broken",
        language="Go",
        stargazers_count=10_000,
        description="Still broken repo.",
        topics=[],
        pushed_at="",
    )
    csv_path = tmp_path / "group_repo.csv"
    write_repo_csv([recovered, still_broken], csv_path)
    output_dir = tmp_path / "final_data"
    output_dir.mkdir()
    failure_log = output_dir / "failed_repos.log"
    failure_log.write_text(
        "2026-06-14T00:00:00+00:00\towner/recovered\tclone\tnetwork failed\n"
        "2026-06-14T00:01:00+00:00\towner/still-broken\tprocess\tbad commit\n",
        encoding="utf-8",
    )
    repo_dir = tmp_path / "repo"
    repo_dir.mkdir()

    monkeypatch.setattr(harvester, "clone_or_update_repo", lambda repo, work_dir, since=None: repo_dir)
    monkeypatch.setattr(harvester, "process_repo_to_commit_jsons", lambda **kwargs: 1)
    monkeypatch.setattr(
        harvester,
        "merge_commit_jsons_to_jsonl",
        lambda commit_dir, final_dir, repo: final_dir / f"{repo.full_name.replace('/', '__')}.jsonl",
    )

    run_pipeline(
        repos=[recovered],
        work_dir=tmp_path / "repos",
        output_dir=output_dir,
        commit_work_dir=tmp_path / "commit_json",
        since="2025-10-01",
        jsonl_workers=1,
        clone_workers=1,
        repo_csv_path=csv_path,
    )

    assert failure_log.read_text(encoding="utf-8").splitlines() == [
        "2026-06-14T00:01:00+00:00\towner/still-broken\tprocess\tbad commit",
    ]


def test_clone_or_update_repo_falls_back_to_full_clone_after_shallow_failure(tmp_path: Path, monkeypatch):
    repo = RepoInfo(
        full_name="owner/project",
        clone_url="https://github.com/owner/project.git",
        html_url="https://github.com/owner/project",
        language="Go",
        stargazers_count=10_000,
        description="Production service.",
        topics=[],
        pushed_at="",
    )
    calls: list[list[str]] = []

    def fake_run_git(args, cwd, capture=False):
        calls.append(list(args))
        if args[:2] == ["clone", "--shallow-since=2025-10-01"]:
            raise subprocess.CalledProcessError(128, ["git", *args], stderr="error processing shallow info: 4")
        return "origin/main\n" if capture else ""

    monkeypatch.setattr(harvester, "run_git", fake_run_git)
    monkeypatch.setattr(harvester, "checkout_origin_head", lambda target: None)

    target = clone_or_update_repo(repo, tmp_path / "repos", since="2025-10-01")

    assert target == tmp_path / "repos" / "owner__project"
    assert calls[0] == [
        "clone",
        "--shallow-since=2025-10-01",
        "https://github.com/owner/project.git",
        str(tmp_path / "repos" / "owner__project"),
    ]
    assert calls[1] == [
        "clone",
        "https://github.com/owner/project.git",
        str(tmp_path / "repos" / "owner__project"),
    ]


def test_select_eligible_repos_skips_filtered_candidates_until_limit():
    tutorial = RepoInfo(
        full_name="owner/awesome-go",
        clone_url="https://github.com/owner/awesome-go.git",
        html_url="https://github.com/owner/awesome-go",
        language="Go",
        stargazers_count=50_000,
        description="A curated list of awesome Go libraries.",
        topics=["awesome"],
        pushed_at="2026-01-02T03:04:05Z",
    )
    production = RepoInfo(
        full_name="owner/server",
        clone_url="https://github.com/owner/server.git",
        html_url="https://github.com/owner/server",
        language="Go",
        stargazers_count=30_000,
        description="Production server runtime.",
        topics=["server"],
        pushed_at="2026-01-02T03:04:05Z",
    )

    assert select_eligible_repos([tutorial, production], max_repos=1) == [production]


def test_code_commit_requires_code_changes_not_docs_or_dependencies():
    assert is_code_commit(
        ["src/app.py", "internal/server/handler.go"],
        code_extensions=CODE_EXTENSIONS,
    )
    assert not is_code_commit(
        ["README.md", "docs/usage.md", "package-lock.json", "poetry.lock"],
        code_extensions=CODE_EXTENSIONS,
    )


def test_project_type_does_not_treat_ui_substrings_as_frontend():
    repo = RepoInfo(
        full_name="fatedier/frp",
        clone_url="https://github.com/fatedier/frp.git",
        html_url="https://github.com/fatedier/frp",
        language="Go",
        stargazers_count=100_000,
        description="A fast reverse proxy to help you expose a local server behind a NAT or firewall.",
        topics=["proxy", "server", "quic"],
        pushed_at="2026-01-02T03:04:05Z",
    )

    assert infer_project_type(repo, ["server/http/controller_v2.go"]) == "网站后端"


def test_build_record_uses_commit_hash_id_and_required_metadata():
    repo = RepoInfo(
        full_name="owner/webapp",
        clone_url="https://github.com/owner/webapp.git",
        html_url="https://github.com/owner/webapp",
        language="JavaScript",
        stargazers_count=12_000,
        description="Frontend web application.",
        topics=["frontend", "react"],
        pushed_at="2026-01-02T03:04:05Z",
    )
    commit = CommitInfo(
        sha="abc123",
        author="Ada Lovelace",
        author_date=dt.datetime(2025, 11, 2, 3, 4, 5, tzinfo=dt.UTC),
        changed_files=["src/App.js"],
    )

    record = build_record(
        repo=repo,
        commit=commit,
        text="console.log('hello');\n",
        project_type="网站前端",
    )

    assert record["id"] == "abc123"
    assert record["text"] == "console.log('hello');\n"
    assert record["meta"]["data_info"] == {
        "lang": "JavaScript",
        "source": "GitHub",
        "url": "https://github.com/owner/webapp",
        "type": "代码",
        "author": "Ada Lovelace",
        "public_date": "2025-11-02T03:04:05+00:00",
        "project_type": "网站前端",
    }


def test_build_record_uses_repo_source_for_gitlab_records():
    repo = RepoInfo(
        full_name="group/project",
        clone_url="https://gitlab.com/group/project.git",
        html_url="https://gitlab.com/group/project",
        language="Python",
        stargazers_count=3_000,
        description="Production data pipeline.",
        topics=["pipeline"],
        pushed_at="2026-01-02T03:04:05Z",
        source="GitLab",
    )
    commit = CommitInfo(
        sha="abc123",
        author="GitLab User",
        author_date=dt.datetime(2025, 11, 2, 3, 4, 5, tzinfo=dt.UTC),
        changed_files=["src/app.py"],
    )

    record = build_record(
        repo=repo,
        commit=commit,
        text="print('hello')\n",
        project_type="通用软件项目",
    )

    assert record["meta"]["data_info"]["source"] == "GitLab"
    assert record["meta"]["data_info"]["url"] == "https://gitlab.com/group/project"


def test_resolve_token_reads_provider_field_from_token_json(tmp_path: Path, monkeypatch):
    token_path = tmp_path / "token.json"
    token_path.write_text(
        json.dumps({"github": "github-json-token", "gitlab": "gitlab-json-token"}),
        encoding="utf-8",
    )
    monkeypatch.delenv("GITHUB_TOKEN", raising=False)

    assert resolve_token(None, "github", "GITHUB_TOKEN", token_path) == "github-json-token"


def test_parse_stackoverflow_args_sets_discussion_defaults():
    args = parse_stackoverflow_args([])

    assert args.output_dir == "final_data_stackoverflow"
    assert args.site == "stackoverflow"
    assert args.tags == ["python", "java", "javascript", "go", "c++"]
    assert args.min_score == 10
    assert args.min_answers == 1
    assert args.page_size == 100


def test_stackoverflow_question_to_record_combines_question_and_answers():
    question = {
        "question_id": 123,
        "title": "How do I parse JSON safely?",
        "body": "<p>I need to parse JSON in Python.</p><pre><code>json.loads(text)</code></pre>",
        "link": "https://stackoverflow.com/questions/123/how-do-i-parse-json-safely",
        "tags": ["python", "json"],
        "score": 42,
        "view_count": 9000,
        "answer_count": 2,
        "creation_date": 1_704_067_200,
        "owner": {"display_name": "Question Author"},
        "answers": [
            {
                "answer_id": 456,
                "body": "<p>Use <code>json.loads</code> and catch the decode error.</p>",
                "score": 81,
                "is_accepted": True,
                "creation_date": 1_704_067_260,
                "owner": {"display_name": "Answer Author"},
            },
            {
                "answer_id": 789,
                "body": "<p>Validate the input first.</p>",
                "score": 3,
                "is_accepted": False,
                "creation_date": 1_704_067_300,
                "owner": {"display_name": "Other Author"},
            },
        ],
    }

    record = stackoverflow_question_to_record(question, tag="python", max_answers=1)

    assert record["id"] == "stackoverflow_question_123"
    assert "Title: How do I parse JSON safely?" in record["text"]
    assert "Question:\nI need to parse JSON in Python." in record["text"]
    assert "json.loads(text)" in record["text"]
    assert "Accepted answer" in record["text"]
    assert "Validate the input first" not in record["text"]
    assert record["meta"]["data_info"] == {
        "source": "StackOverflow",
        "type": "技术问答",
        "url": "https://stackoverflow.com/questions/123/how-do-i-parse-json-safely",
        "license": "CC BY-SA 4.0",
        "site": "stackoverflow",
        "tag": "python",
        "tags": ["python", "json"],
        "score": 42,
        "views": 9000,
        "answer_count": 2,
        "author": "Question Author",
        "public_date": "2024-01-01T00:00:00+00:00",
    }


def test_write_stackoverflow_records_outputs_jsonl(tmp_path: Path):
    output_path = tmp_path / "final_data_stackoverflow" / "stackoverflow_python.jsonl"
    records = [
        {
            "id": "stackoverflow_question_1",
            "text": "question and answer",
            "meta": {"data_info": {"source": "StackOverflow"}},
        }
    ]

    written = write_stackoverflow_records(records, output_path)

    assert written == 1
    assert json.loads(output_path.read_text(encoding="utf-8")) == records[0]


def test_resolve_token_prefers_cli_value_then_falls_back_to_env(tmp_path: Path, monkeypatch):
    token_path = tmp_path / "token.json"
    token_path.write_text(json.dumps({"github": "github-json-token"}), encoding="utf-8")
    monkeypatch.setenv("GITLAB_TOKEN", "gitlab-env-token")

    assert resolve_token("cli-token", "github", "GITHUB_TOKEN", token_path) == "cli-token"
    assert resolve_token(None, "gitlab", "GITLAB_TOKEN", token_path) == "gitlab-env-token"


def test_gitlab_main_does_not_read_token_json_by_default(tmp_path: Path, monkeypatch):
    token_path = tmp_path / "token.json"
    token_path.write_text(
        json.dumps({"gitlab": "bad-token-from-json"}),
        encoding="utf-8",
    )
    seen: dict[str, str | None] = {}

    def fake_fetch_project(
        project_path: str,
        gitlab_base_url: str = "https://gitlab.com",
        gitlab_token: str | None = None,
    ) -> RepoInfo:
        seen["token"] = gitlab_token
        return RepoInfo(
            full_name=project_path,
            clone_url=f"https://gitlab.com/{project_path}.git",
            html_url=f"https://gitlab.com/{project_path}",
            language="Go",
            stargazers_count=1200,
            description="Production runner.",
            topics=[],
            pushed_at="",
            source="GitLab",
        )

    monkeypatch.chdir(tmp_path)
    monkeypatch.delenv("GITLAB_TOKEN", raising=False)
    monkeypatch.setattr(harvester, "fetch_gitlab_project", fake_fetch_project)
    monkeypatch.setattr(harvester, "run_pipeline", lambda **kwargs: None)

    assert harvester.gitlab_main(["--repo", "group/project"]) == 0

    assert seen["token"] is None


def test_gitlab_project_to_repo_maps_api_payload():
    repo = gitlab_project_to_repo(
        {
            "path_with_namespace": "group/project",
            "http_url_to_repo": "https://gitlab.com/group/project.git",
            "web_url": "https://gitlab.com/group/project",
            "star_count": 4567,
            "description": "A backend API service.",
            "topics": ["api"],
            "last_activity_at": "2026-01-02T03:04:05Z",
        },
        language="Python",
    )

    assert repo == RepoInfo(
        full_name="group/project",
        clone_url="https://gitlab.com/group/project.git",
        html_url="https://gitlab.com/group/project",
        language="Python",
        stargazers_count=4567,
        description="A backend API service.",
        topics=["api"],
        pushed_at="2026-01-02T03:04:05Z",
        source="GitLab",
    )


def test_fetch_gitlab_project_uses_encoded_namespace_and_private_token(monkeypatch):
    seen: dict[str, object] = {}

    def fake_get_json(url: str, token: str | None) -> dict:
        seen["url"] = url
        seen["token"] = token
        return {
            "path_with_namespace": "group/sub/project",
            "http_url_to_repo": "https://gitlab.example.com/group/sub/project.git",
            "web_url": "https://gitlab.example.com/group/sub/project",
            "star_count": 12,
            "description": "Internal service.",
            "topics": [],
            "last_activity_at": "2026-01-02T03:04:05Z",
        }

    monkeypatch.setattr(harvester, "gitlab_get_json", fake_get_json)

    repo = fetch_gitlab_project(
        "group/sub/project",
        gitlab_base_url="https://gitlab.example.com",
        gitlab_token="secret",
    )

    assert seen == {
        "url": "https://gitlab.example.com/api/v4/projects/group%2Fsub%2Fproject",
        "token": "secret",
    }
    assert repo.full_name == "group/sub/project"
    assert repo.source == "GitLab"


def test_fetch_high_star_gitlab_projects_searches_by_language_and_filters(monkeypatch):
    calls: list[str] = []

    def fake_get_json(url: str, token: str | None) -> list[dict]:
        calls.append(url)
        return [
            {
                "path_with_namespace": "group/tutorial",
                "http_url_to_repo": "https://gitlab.com/group/tutorial.git",
                "web_url": "https://gitlab.com/group/tutorial",
                "star_count": 9000,
                "description": "Tutorial project.",
                "topics": ["tutorial"],
                "last_activity_at": "2026-01-02T03:04:05Z",
            },
            {
                "path_with_namespace": "group/exact-threshold",
                "http_url_to_repo": "https://gitlab.com/group/exact-threshold.git",
                "web_url": "https://gitlab.com/group/exact-threshold",
                "star_count": 5000,
                "description": "Production backend service.",
                "topics": ["api"],
                "last_activity_at": "2026-01-02T03:04:05Z",
            },
            {
                "path_with_namespace": "group/archived",
                "http_url_to_repo": "https://gitlab.com/group/archived.git",
                "web_url": "https://gitlab.com/group/archived",
                "star_count": 7000,
                "description": "Production backend service.",
                "topics": ["api"],
                "archived": True,
                "last_activity_at": "2026-01-02T03:04:05Z",
            },
            {
                "path_with_namespace": "group/mirror",
                "http_url_to_repo": "https://gitlab.com/group/mirror.git",
                "web_url": "https://gitlab.com/group/mirror",
                "star_count": 7000,
                "description": "Production backend service.",
                "topics": ["api"],
                "mirror": True,
                "last_activity_at": "2026-01-02T03:04:05Z",
            },
            {
                "path_with_namespace": "group/service",
                "http_url_to_repo": "https://gitlab.com/group/service.git",
                "web_url": "https://gitlab.com/group/service",
                "star_count": 8000,
                "description": "Production backend service.",
                "topics": ["api"],
                "last_activity_at": "2026-01-02T03:04:05Z",
            },
        ]

    monkeypatch.setattr(harvester, "gitlab_get_json", fake_get_json)

    repos = fetch_high_star_gitlab_projects(
        languages=["Python"],
        min_stars=5000,
        repos_per_language=10,
        gitlab_base_url="https://gitlab.com",
        gitlab_token=None,
        max_repos=1,
    )

    assert len(repos) == 1
    assert repos[0].full_name == "group/service"
    assert repos[0].source == "GitLab"
    assert "with_programming_language=Python" in calls[0]
    assert "order_by=star_count" in calls[0]


def test_fetch_high_star_gitlab_projects_caps_api_page_size(monkeypatch):
    calls: list[str] = []

    def fake_get_json(url: str, token: str | None) -> list[dict]:
        calls.append(url)
        return [
            {
                "path_with_namespace": "group/service",
                "http_url_to_repo": "https://gitlab.com/group/service.git",
                "web_url": "https://gitlab.com/group/service",
                "star_count": 8000,
                "description": "Production backend service.",
                "topics": ["api"],
                "last_activity_at": "2026-01-02T03:04:05Z",
            },
        ]

    monkeypatch.setattr(harvester, "gitlab_get_json", fake_get_json)

    repos = fetch_high_star_gitlab_projects(
        languages=["Go"],
        min_stars=1000,
        repos_per_language=100,
        gitlab_base_url="https://gitlab.com",
        gitlab_token=None,
        max_repos=1,
    )

    assert len(repos) == 1
    query = urllib.parse.parse_qs(urllib.parse.urlparse(calls[0]).query)
    assert query["per_page"] == ["10"]


def test_fetch_high_star_gitlab_projects_continues_beyond_ten_pages_when_needed(monkeypatch):
    calls: list[str] = []

    def fake_get_json(url: str, token: str | None) -> list[dict]:
        calls.append(url)
        query = urllib.parse.parse_qs(urllib.parse.urlparse(url).query)
        page = int(query["page"][0])
        return [
            {
                "path_with_namespace": f"group/service-{page}",
                "http_url_to_repo": f"https://gitlab.com/group/service-{page}.git",
                "web_url": f"https://gitlab.com/group/service-{page}",
                "star_count": 8000 - page,
                "description": "Production backend service.",
                "topics": ["api"],
                "last_activity_at": "2026-01-02T03:04:05Z",
            }
        ]

    monkeypatch.setattr(harvester, "gitlab_get_json", fake_get_json)

    repos = fetch_high_star_gitlab_projects(
        languages=["Go"],
        min_stars=1000,
        repos_per_language=11,
        gitlab_base_url="https://gitlab.com",
        gitlab_token=None,
        max_repos=11,
    )

    assert len(repos) == 11
    assert repos[-1].full_name == "group/service-11"
    assert len(calls) == 11


def test_write_jsonl_for_commit_writes_one_record_with_all_code(tmp_path: Path):
    repo_dir = tmp_path / "repo"
    repo_dir.mkdir()
    (repo_dir / "src").mkdir()
    (repo_dir / "src" / "app.py").write_text("print('ok')\n", encoding="utf-8")
    (repo_dir / "src" / "worker.py").write_text("print('worker')\n", encoding="utf-8")
    (repo_dir / "README.md").write_text("# docs\n", encoding="utf-8")
    output = tmp_path / "out.jsonl"
    repo = RepoInfo(
        full_name="owner/tool",
        clone_url="https://github.com/owner/tool.git",
        html_url="https://github.com/owner/tool",
        language="Python",
        stargazers_count=15_000,
        description="Production command line tool.",
        topics=["cli"],
        pushed_at="2026-01-02T03:04:05Z",
    )
    commit = CommitInfo(
        sha="def456",
        author="Grace Hopper",
        author_date=dt.datetime(2025, 12, 1, tzinfo=dt.UTC),
        changed_files=["src/app.py", "README.md", "src/worker.py"],
    )

    count = write_jsonl_for_commit(repo_dir, output, repo, commit)

    rows = [json.loads(line) for line in output.read_text(encoding="utf-8").splitlines()]
    assert count == 1
    assert len(rows) == 1
    assert rows[0]["id"] == "def456"
    assert rows[0]["text"] == "print('ok')\n\nprint('worker')\n"
    assert rows[0]["meta"]["data_info"]["url"] == "https://github.com/owner/tool"


def test_write_jsonl_merges_mixed_commit_into_one_record(tmp_path: Path):
    repo_dir = tmp_path / "repo"
    (repo_dir / "server").mkdir(parents=True)
    (repo_dir / "web" / "src").mkdir(parents=True)
    (repo_dir / "server" / "handler.go").write_text("package server\n", encoding="utf-8")
    (repo_dir / "web" / "src" / "api.ts").write_text("export const api = 1;\n", encoding="utf-8")
    output = tmp_path / "out.jsonl"
    repo = RepoInfo(
        full_name="owner/mixed",
        clone_url="https://github.com/owner/mixed.git",
        html_url="https://github.com/owner/mixed",
        language="Go",
        stargazers_count=15_000,
        description="A server with a small web UI.",
        topics=["server", "quic"],
        pushed_at="2026-01-02T03:04:05Z",
    )
    commit = CommitInfo(
        sha="abc789",
        author="Maintainer",
        author_date=dt.datetime(2026, 6, 1, tzinfo=dt.UTC),
        changed_files=["server/handler.go", "web/src/api.ts"],
    )

    write_jsonl_for_commit(repo_dir, output, repo, commit)

    rows = [json.loads(line) for line in output.read_text(encoding="utf-8").splitlines()]
    assert len(rows) == 1
    assert rows[0]["id"] == "abc789"
    assert rows[0]["text"] == "package server\n\nexport const api = 1;\n"


def test_process_repo_outputs_one_record_per_commit(tmp_path: Path):
    repo_dir = tmp_path / "repo"
    repo_dir.mkdir()
    subprocess.run(["git", "init"], cwd=repo_dir, check=True, stdout=subprocess.DEVNULL)
    subprocess.run(
        ["git", "-c", "user.name=Test User", "-c", "user.email=test@example.com", "commit", "--allow-empty", "-m", "init"],
        cwd=repo_dir,
        check=True,
        stdout=subprocess.DEVNULL,
        env={
            **os.environ,
            "GIT_AUTHOR_DATE": "2025-09-01T00:00:00+00:00",
            "GIT_COMMITTER_DATE": "2025-09-01T00:00:00+00:00",
        },
    )
    (repo_dir / "main.py").write_text("print('main')\n", encoding="utf-8")
    (repo_dir / "worker.py").write_text("print('worker')\n", encoding="utf-8")
    subprocess.run(["git", "add", "main.py", "worker.py"], cwd=repo_dir, check=True)
    subprocess.run(
        ["git", "-c", "user.name=Test User", "-c", "user.email=test@example.com", "commit", "-m", "add code"],
        cwd=repo_dir,
        check=True,
        stdout=subprocess.DEVNULL,
        env={
            **os.environ,
            "GIT_AUTHOR_DATE": "2025-11-01T00:00:00+00:00",
            "GIT_COMMITTER_DATE": "2025-11-01T00:00:00+00:00",
        },
    )
    sha = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=repo_dir,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
    ).stdout.strip()
    repo = RepoInfo(
        full_name="owner/local",
        clone_url="https://github.com/owner/local.git",
        html_url="https://github.com/owner/local",
        language="Python",
        stargazers_count=10_000,
        description="Command line tool.",
        topics=["cli"],
        pushed_at="2026-01-02T03:04:05Z",
    )

    count = process_repo(repo, repo_dir, tmp_path / "out", since="2025-10-01")

    rows = [
        json.loads(line)
        for line in (tmp_path / "out" / "owner__local.jsonl").read_text(encoding="utf-8").splitlines()
    ]
    assert count == 1
    assert len(rows) == 1
    assert rows[0]["id"] == sha
    assert rows[0]["text"] == "print('main')\n\nprint('worker')\n"


def test_checkout_commit_discards_dirty_cache_changes(tmp_path: Path):
    repo_dir = tmp_path / "repo"
    repo_dir.mkdir()
    subprocess.run(["git", "init"], cwd=repo_dir, check=True, stdout=subprocess.DEVNULL)
    (repo_dir / "file.py").write_text("print('one')\n", encoding="utf-8")
    subprocess.run(["git", "add", "file.py"], cwd=repo_dir, check=True)
    subprocess.run(
        ["git", "-c", "user.name=Test User", "-c", "user.email=test@example.com", "commit", "-m", "one"],
        cwd=repo_dir,
        check=True,
        stdout=subprocess.DEVNULL,
    )
    first_sha = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=repo_dir,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
    ).stdout.strip()
    (repo_dir / "file.py").write_text("print('two')\n", encoding="utf-8")
    subprocess.run(["git", "add", "file.py"], cwd=repo_dir, check=True)
    subprocess.run(
        ["git", "-c", "user.name=Test User", "-c", "user.email=test@example.com", "commit", "-m", "two"],
        cwd=repo_dir,
        check=True,
        stdout=subprocess.DEVNULL,
    )

    (repo_dir / "file.py").write_text("dirty cache change\n", encoding="utf-8")
    (repo_dir / "temp.txt").write_text("remove me\n", encoding="utf-8")

    checkout_commit(repo_dir, first_sha)

    assert (repo_dir / "file.py").read_text(encoding="utf-8") == "print('one')\n"
    assert not (repo_dir / "temp.txt").exists()


def test_process_repo_to_commit_jsons_merges_and_cleans_workspace(tmp_path: Path):
    repo_dir = tmp_path / "repo"
    repo_dir.mkdir()
    subprocess.run(["git", "init"], cwd=repo_dir, check=True, stdout=subprocess.DEVNULL)
    subprocess.run(
        ["git", "-c", "user.name=Test User", "-c", "user.email=test@example.com", "commit", "--allow-empty", "-m", "init"],
        cwd=repo_dir,
        check=True,
        stdout=subprocess.DEVNULL,
        env={
            **os.environ,
            "GIT_AUTHOR_DATE": "2025-09-01T00:00:00+00:00",
            "GIT_COMMITTER_DATE": "2025-09-01T00:00:00+00:00",
        },
    )
    (repo_dir / "server").mkdir()
    (repo_dir / "server" / "main.go").write_text("package main\n", encoding="utf-8")
    subprocess.run(["git", "add", "server/main.go"], cwd=repo_dir, check=True)
    subprocess.run(
        ["git", "-c", "user.name=Test User", "-c", "user.email=test@example.com", "commit", "-m", "add server"],
        cwd=repo_dir,
        check=True,
        stdout=subprocess.DEVNULL,
        env={
            **os.environ,
            "GIT_AUTHOR_DATE": "2025-11-01T00:00:00+00:00",
            "GIT_COMMITTER_DATE": "2025-11-01T00:00:00+00:00",
        },
    )
    sha = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=repo_dir,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
    ).stdout.strip()
    repo = RepoInfo(
        full_name="owner/local",
        clone_url="https://github.com/owner/local.git",
        html_url="https://github.com/owner/local",
        language="Go",
        stargazers_count=10_000,
        description="Production backend server.",
        topics=["server"],
        pushed_at="2026-01-02T03:04:05Z",
    )
    commit_dir = tmp_path / "commits" / "owner__local"
    final_dir = tmp_path / "final_data"

    count = process_repo_to_commit_jsons(repo, repo_dir, commit_dir, since="2025-10-01")
    final_path = merge_commit_jsons_to_jsonl(commit_dir, final_dir, repo)
    cleanup_project_workspace(repo_dir, commit_dir)

    rows = [json.loads(line) for line in final_path.read_text(encoding="utf-8").splitlines()]
    assert count == 1
    assert (commit_dir / f"{sha}.json").exists() is False
    assert repo_dir.exists() is False
    assert final_path.name == "owner__local.jsonl"
    assert rows[0]["id"] == sha
    assert rows[0]["text"] == "package main\n"


def test_merge_commit_jsons_does_not_create_final_file_when_empty(tmp_path: Path):
    repo = RepoInfo(
        full_name="owner/empty",
        clone_url="https://github.com/owner/empty.git",
        html_url="https://github.com/owner/empty",
        language="Go",
        stargazers_count=10_000,
        description="No matching code commits.",
        topics=[],
        pushed_at="",
    )
    commit_dir = tmp_path / "commits" / "owner__empty"
    final_dir = tmp_path / "final_data"
    commit_dir.mkdir(parents=True)
    final_dir.mkdir()
    old_empty = final_dir / "owner__empty.jsonl"
    old_empty.touch()

    final_path = merge_commit_jsons_to_jsonl(commit_dir, final_dir, repo)

    assert final_path is None
    assert not old_empty.exists()
